## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports Clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports Clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {A[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN W17 [get_ports {A[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property PACKAGE_PIN W15 [get_ports {A[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[4]}]
set_property PACKAGE_PIN V15 [get_ports {A[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[5]}]
set_property PACKAGE_PIN W14 [get_ports {A[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[6]}]
set_property PACKAGE_PIN W13 [get_ports {A[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[7]}]
set_property PACKAGE_PIN V2 [get_ports {B[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property PACKAGE_PIN T3 [get_ports {B[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property PACKAGE_PIN T2 [get_ports {B[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property PACKAGE_PIN R3 [get_ports {B[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property PACKAGE_PIN W2 [get_ports {B[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[4]}]
set_property PACKAGE_PIN U1 [get_ports {B[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[5]}]
set_property PACKAGE_PIN T1 [get_ports {B[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[6]}]
set_property PACKAGE_PIN R2 [get_ports {B[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[7]}]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports {res[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[0]}]
set_property PACKAGE_PIN E19 [get_ports {res[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[1]}]
set_property PACKAGE_PIN U19 [get_ports {res[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[2]}]
set_property PACKAGE_PIN V19 [get_ports {res[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[3]}]
set_property PACKAGE_PIN W18 [get_ports {res[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[4]}]
set_property PACKAGE_PIN U15 [get_ports {res[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[5]}]
set_property PACKAGE_PIN U14 [get_ports {res[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[6]}]
set_property PACKAGE_PIN V14 [get_ports {res[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[7]}]
set_property PACKAGE_PIN V13 [get_ports {res[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[8]}]
set_property PACKAGE_PIN V3 [get_ports {res[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[9]}]
set_property PACKAGE_PIN W3 [get_ports {res[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[10]}]
set_property PACKAGE_PIN U3 [get_ports {res[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[11]}]
set_property PACKAGE_PIN P3 [get_ports {res[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[12]}]
set_property PACKAGE_PIN N3 [get_ports {res[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[13]}]
set_property PACKAGE_PIN P1 [get_ports {res[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[14]}]
set_property PACKAGE_PIN L1 [get_ports {res[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {res[15]}]
	
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]  
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]


set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]


##Buttons
set_property PACKAGE_PIN T18 [get_ports Start]						
	set_property IOSTANDARD LVCMOS33 [get_ports Start]